import React, { useState, useEffect, useRef } from 'react';

export default function App() {
  const [sessionToken, setSessionToken] = useState(() => {
    return localStorage.getItem('watermark_session_token') || '';
  });
  
  const [files, setFiles] = useState([]);
  const [jobId, setJobId] = useState('');
  const [jobStatus, setJobStatus] = useState('IDLE'); // IDLE, UPLOADED, QUEUED, PROCESSING, DONE, FAILED
  const [jobProgress, setJobProgress] = useState(0);
  const [dragActive, setDragActive] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [isUploading, setIsUploading] = useState(false);
  const [activePreviewUrl, setActivePreviewUrl] = useState(null);

  const fileInputRef = useRef(null);
  const pollTimerRef = useRef(null);

  // Initialize session token on first request if empty
  useEffect(() => {
    if (!sessionToken) {
      // Create session UUID or let Gateway return it in response headers
      // We will send a probe or wait for first API call to return header
      // Since gateway assigns a token when none is provided, we can fetch token
      // in any request and extract the X-Session-Token header.
    }
  }, [sessionToken]);

  // Clean up polling timer on unmount
  useEffect(() => {
    return () => {
      if (pollTimerRef.current) clearInterval(pollTimerRef.current);
    };
  }, []);

  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFiles(Array.from(e.dataTransfer.files));
    }
  };

  const handleFileInput = (e) => {
    if (e.target.files && e.target.files[0]) {
      handleFiles(Array.from(e.target.files));
    }
  };

  const validateFile = (file) => {
    const allowedTypes = ['image/jpeg', 'image/png', 'image/webp'];
    const maxBytes = 10 * 1024 * 1024; // 10MB limit

    if (!allowedTypes.includes(file.type)) {
      return `File '${file.name}' is not supported. Only JPEG, PNG, and WEBP are allowed.`;
    }
    if (file.size > maxBytes) {
      return `File '${file.name}' exceeds the 10MB size limit.`;
    }
    return null;
  };

  const handleFiles = (incomingFiles) => {
    if (isUploading || jobStatus === 'PROCESSING' || jobStatus === 'QUEUED') return;

    setErrorMsg('');
    const validated = [];
    const errors = [];

    incomingFiles.forEach(file => {
      const err = validateFile(file);
      if (err) {
        errors.push(err);
      } else {
        validated.push({
          file,
          id: Math.random().toString(36).substr(2, 9),
          name: file.name,
          preview: URL.createObjectURL(file),
          status: 'READY',
          progress: 0,
          downloadUrl: '',
          error: ''
        });
      }
    });

    if (errors.length > 0) {
      setErrorMsg(errors.join(' | '));
    }

    if (validated.length > 0) {
      setFiles(validated);
      setJobStatus('IDLE');
      setJobProgress(0);
      setJobId('');
    }
  };

  const startUpload = async () => {
    if (files.length === 0 || isUploading) return;

    setIsUploading(true);
    setErrorMsg('');
    setJobStatus('UPLOADED');

    const formData = new FormData();
    files.forEach(f => {
      formData.append('images', f.file);
    });

    const headers = {};
    if (sessionToken) {
      headers['X-Session-Token'] = sessionToken;
    }

    try {
      const response = await fetch('/api/upload', {
        method: 'POST',
        headers: headers,
        body: formData
      });

      // Capture returned session token if generated by server
      const returnedToken = response.headers.get('X-Session-Token');
      if (returnedToken && returnedToken !== sessionToken) {
        setSessionToken(returnedToken);
        localStorage.setItem('watermark_session_token', returnedToken);
      }

      if (response.status === 429) {
        throw new Error('Rate limit exceeded. Please wait a minute before trying again.');
      }

      if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error || 'Failed to upload images.');
      }

      const data = await response.json();
      setJobId(data.job_id);
      setJobStatus('QUEUED');
      
      // Update local status to QUEUED
      setFiles(prev => prev.map(f => ({ ...f, status: 'QUEUED' })));

      // Begin polling
      startPolling(data.job_id, returnedToken || sessionToken);

    } catch (err) {
      setErrorMsg(err.message);
      setJobStatus('FAILED');
      setFiles(prev => prev.map(f => ({ ...f, status: 'FAILED', error: err.message })));
    } finally {
      setIsUploading(false);
    }
  };

  const startPolling = (targetJobId, token) => {
    if (pollTimerRef.current) clearInterval(pollTimerRef.current);

    pollTimerRef.current = setInterval(async () => {
      try {
        const headers = {};
        if (token) {
          headers['X-Session-Token'] = token;
        }

        const res = await fetch(`/api/job/${targetJobId}`, { headers });
        if (res.status === 429) return; // Ignore transient rate limit ticks during polling
        
        if (!res.ok) {
          throw new Error('Failed to retrieve job status.');
        }

        const data = await res.json();
        setJobStatus(data.status);
        setJobProgress(data.progress);

        // Map server file states back to local previews
        setFiles(prev => {
          return prev.map((localFile, idx) => {
            const serverFile = data.files[idx];
            if (!serverFile) return localFile;

            return {
              ...localFile,
              status: serverFile.status,
              downloadUrl: serverFile.download_url || '',
              error: serverFile.error || ''
            };
          });
        });

        // Terminate polling on terminal states
        if (data.status === 'DONE' || data.status === 'FAILED') {
          clearInterval(pollTimerRef.current);
          pollTimerRef.current = null;
        }

      } catch (err) {
        console.error("Polling error:", err);
        setErrorMsg('Error checking job status. Re-trying...');
      }
    }, 2000);
  };

  const triggerDownload = (downloadUrl) => {
    if (!downloadUrl) return;
    const a = document.createElement('a');
    a.href = downloadUrl;
    // Download name will be resolved by Content-Disposition or download attribute
    a.setAttribute('download', '');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const downloadAllAsZip = () => {
    if (!jobId || jobStatus !== 'DONE') return;
    // We append session token as query param so gateway validates session for direct link downloads
    window.location.href = `/api/download-zip/${jobId}?token=${sessionToken}`;
  };

  const clearWorkspace = () => {
    setFiles([]);
    setJobId('');
    setJobStatus('IDLE');
    setJobProgress(0);
    setErrorMsg('');
  };

  return (
    <div className="container">
      <div className="glow-backdrop"></div>
      
      <header>
        <h1>Secure Watermark Eraser</h1>
        <p>Asynchronous AI Watermark Detection & Noise Removal Microservice</p>
      </header>

      <div className="panel">
        <div 
          className={`dropzone ${dragActive ? 'active' : ''}`}
          onDragEnter={handleDrag}
          onDragOver={handleDrag}
          onDragLeave={handleDrag}
          onDrop={handleDrop}
          onClick={() => fileInputRef.current.click()}
        >
          <input 
            type="file" 
            ref={fileInputRef}
            style={{ display: 'none' }} 
            multiple 
            accept=".jpg,.jpeg,.png,.webp"
            onChange={handleFileInput}
            disabled={isUploading || jobStatus === 'PROCESSING' || jobStatus === 'QUEUED'}
          />
          <span className="dropzone-icon">✨</span>
          <h3>Drag & Drop your images here</h3>
          <p>Supports JPEG, PNG, WEBP up to 10MB each</p>
        </div>

        {errorMsg && (
          <div style={{
            color: 'var(--danger)',
            fontSize: '0.9rem',
            marginTop: '1rem',
            padding: '0.75rem',
            background: 'rgba(239, 68, 68, 0.08)',
            border: '1px solid rgba(239, 68, 68, 0.2)',
            borderRadius: 'var(--radius-md)',
            textAlign: 'center'
          }}>
            {errorMsg}
          </div>
        )}

        {files.length > 0 && (
          <div className="btn-group">
            <button 
              className="btn btn-primary"
              onClick={startUpload}
              disabled={isUploading || jobStatus === 'PROCESSING' || jobStatus === 'QUEUED' || jobStatus === 'DONE'}
            >
              {isUploading ? 'Uploading...' : 'Process Watermarks'}
            </button>
            <button 
              className="btn btn-secondary"
              onClick={clearWorkspace}
              disabled={isUploading || jobStatus === 'PROCESSING' || jobStatus === 'QUEUED'}
            >
              Clear
            </button>
            {jobStatus === 'DONE' && (
              <button 
                className="btn btn-primary"
                style={{ background: 'linear-gradient(90deg, var(--primary) 0%, var(--accent) 100%)' }}
                onClick={downloadAllAsZip}
              >
                📦 Download All as ZIP
              </button>
            )}
          </div>
        )}
      </div>

      {jobStatus !== 'IDLE' && (
        <div className="panel" style={{ background: 'rgba(15, 23, 42, 0.3)' }}>
          <div className="progress-container">
            <div className="progress-label-row">
              <span style={{ fontWeight: 600 }}>Job Status: <span className={`badge badge-${jobStatus.toLowerCase()}`}>{jobStatus}</span></span>
              <span>{jobProgress}%</span>
            </div>
            <div className="progress-track">
              <div className="progress-fill" style={{ width: `${jobProgress}%` }}></div>
            </div>
          </div>
        </div>
      )}

      {files.length > 0 && (
        <div>
          <h2 style={{ fontSize: '1.4rem', fontWeight: 600, marginBottom: '1rem' }}>Images Queue ({files.length})</h2>
          <div className="preview-grid">
            {files.map((file) => (
              <div className="preview-card" key={file.id}>
                <div 
                  className="preview-image-wrapper"
                  onClick={() => setActivePreviewUrl((file.status === 'DONE' && file.downloadUrl) ? file.downloadUrl : file.preview)}
                  title="Click to view full image"
                >
                  <img 
                    src={(file.status === 'DONE' && file.downloadUrl) ? file.downloadUrl : file.preview} 
                    alt={file.name} 
                    className="preview-image" 
                  />
                </div>
                
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <span style={{
                    fontSize: '0.85rem',
                    fontWeight: 600,
                    whiteSpace: 'nowrap',
                    overflow: 'hidden',
                    textOverflow: 'ellipsis'
                  }} title={file.name}>
                    {file.name}
                  </span>
                  <span className={`badge badge-${file.status.toLowerCase()}`}>
                    {file.status}
                  </span>
                </div>

                {file.status === 'DONE' && file.downloadUrl && (
                  <button 
                    className="btn btn-secondary"
                    style={{ marginTop: 'auto', width: '100%', borderColor: 'var(--success)' }}
                    onClick={() => triggerDownload(file.downloadUrl)}
                  >
                    ⬇️ Download Processed
                  </button>
                )}

                {file.status === 'FAILED' && (
                  <span style={{ fontSize: '0.8rem', color: 'var(--danger)', marginTop: 'auto' }}>
                    ❌ {file.error || 'Failed'}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {activePreviewUrl && (
        <div className="image-modal-overlay" onClick={() => setActivePreviewUrl(null)}>
          <button className="image-modal-close" onClick={() => setActivePreviewUrl(null)}>&times;</button>
          <img 
            src={activePreviewUrl} 
            alt="Fullscreen preview" 
            className="image-modal-content" 
            onClick={(e) => e.stopPropagation()} 
          />
        </div>
      )}
    </div>
  );
}
